export * from './Home/Home'
export * from './Delivery/Delivery'
export * from './Brands/Brands'
export * from './PersonalArea/PersonalArea'
export * from './ProductDescritpion/ProductDescription'
export * from './Basket/Basket'
export * from './Refund/Refund'